name: Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bbonkr/get-version-action@v1.0.4
        id: get_version
        with:
          project: "./package.json"
      - name: logging
        run: |
          echo "Version=${{ steps.get_version.outputs.version }}"
