name: Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: bbonkr/get-version-action@v1.0.4 #steps.get_version.outputs.version
        id: get_version
        with:
          project: "./package.json"
      ## check if artifact exists
      - name: Check if artifact exists
        id: check_artifact
        uses: actions/github-script@v6
        with:
          script: |
            const artifact = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            const artifactExists = artifact.data.artifacts.some((artifact) => artifact.name === 'cicd-project-1_v${{ steps.get_version.outputs.version }}')
            return artifactExists
      ## if artifact exists, skip build and log message
      - name: Skip build
        if: steps.check_artifact.outputs.result == 'true'
        run: |
          echo "Artifact already exists"
      ## if artifact does not exist, build and upload artifact
      - name: Use Node.js 18
        if: steps.check_artifact.outputs.result != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        if: steps.check_artifact.outputs.result != 'true'
        run: npm ci

      - name: Build app
        if: steps.check_artifact.outputs.result != 'true'
        run: npm run build

      - name: Run tests
        if: steps.check_artifact.outputs.result != 'true'
        run: npm run test:ci -- -u

      - name: Upload artifact
        if: steps.check_artifact.outputs.result != 'true'
        uses: actions/upload-artifact@v3
        with:
          name: cicd-project-1_v${{ steps.get_version.outputs.version }}
          path: |
            ./.next
            ./package.json
            ./package-lock.json
          retention-days: 1
